#include <emscripten/bind.h>
#include <emscripten/fetch.h>
#include <emscripten.h>

#include <cstring>
#include <fstream>
#include <iostream>
#include <string>

// 1. GET request example
void get_request_example() {
  emscripten_fetch_attr_t attr;
  emscripten_fetch_attr_init(&attr);

  strcpy(attr.requestMethod, "GET");  // Set the request method to GET
  attr.attributes =
      EMSCRIPTEN_FETCH_LOAD_TO_MEMORY |
      EMSCRIPTEN_FETCH_REPLACE;

  // Set success and error callbacks
  attr.onsuccess = [](emscripten_fetch_t* fetch) {
    std::string response(fetch->data, fetch->numBytes);

    std::cout << "Status: " << fetch->status << std::endl;
    std::cout << "Response: " << response << std::endl;

    emscripten_fetch_close(fetch);
  };

  attr.onerror = [](emscripten_fetch_t* fetch) {
    std::string response =
        fetch->data
            ? std::string(fetch->data, fetch->numBytes)
            : std::string{};

    std::cerr << "Status: " << fetch->status << std::endl;
    std::cerr << "Response: " << response << std::endl;

    emscripten_fetch_close(fetch);
  };

  emscripten_fetch_t* fetch
    = emscripten_fetch(&attr, "http://localhost:3000/hello");
  if (!fetch) {
    std::cerr << "Failed to start request" << std::endl;
  }
}

// 2. GET request with authorization header example
// Use withAuth to test requests both with and without an Authorization header
void get_request_with_auth_example(bool withAuth) {
  emscripten_fetch_attr_t attr;
  emscripten_fetch_attr_init(&attr);

  strcpy(attr.requestMethod, "GET");  // Set the request method to GET
  attr.attributes =
      EMSCRIPTEN_FETCH_LOAD_TO_MEMORY |
      EMSCRIPTEN_FETCH_REPLACE;

  // Set the Authorization header
  if (withAuth) {
    const char* headers[] = {
      "Authorization", "Bearer test-token",
      nullptr
    };
    attr.requestHeaders = headers;
  }

  // Set success and error callbacks
  attr.onsuccess = [](emscripten_fetch_t* fetch) {
    std::string response(fetch->data, fetch->numBytes);

    std::cout << "Status: " << fetch->status << std::endl;
    std::cout << "Response: " << response << std::endl;

    emscripten_fetch_close(fetch);
  };

  attr.onerror = [](emscripten_fetch_t* fetch) {
    std::string response =
        fetch->data
            ? std::string(fetch->data, fetch->numBytes)
            : std::string{};

    std::cerr << "Status: " << fetch->status << std::endl;
    std::cerr << "Response: " << response << std::endl;

    emscripten_fetch_close(fetch);
  };

  emscripten_fetch_t* fetch
    = emscripten_fetch(&attr, "http://localhost:3000/auth");
  if (!fetch) {
    std::cerr << "Failed to start request" << std::endl;
  }
}

// 3. POST request with body example
void post_request_with_body_example(const std::string& body) {
  emscripten_fetch_attr_t attr;
  emscripten_fetch_attr_init(&attr);

  strcpy(attr.requestMethod, "POST");  // Set the request method to POST
  attr.attributes =
      EMSCRIPTEN_FETCH_LOAD_TO_MEMORY |
      EMSCRIPTEN_FETCH_REPLACE;

  // Set request headers
  const char* headers[] = {
    "Content-Type", "application/json",
    nullptr
  };
  attr.requestHeaders = headers;

  // Set the request body
  auto* requestBody = new std::string(body);
  attr.requestData = requestBody->data();
  attr.requestDataSize = requestBody->size();

  // Store requestBody in userData so the callbacks can release it
  attr.userData = requestBody;

  // Set success and error callbacks
  attr.onsuccess = [](emscripten_fetch_t* fetch) {
    std::string response(fetch->data, fetch->numBytes);

    std::cout << "Status: " << fetch->status << std::endl;
    std::cout << "Response: " << response << std::endl;

    // Release requestBody
    delete static_cast<std::string*>(fetch->userData);
    emscripten_fetch_close(fetch);
  };

  attr.onerror = [](emscripten_fetch_t* fetch) {
    std::string response =
        fetch->data
            ? std::string(fetch->data, fetch->numBytes)
            : std::string{};

    std::cerr << "Status: " << fetch->status << std::endl;
    std::cerr << "Response: " << response << std::endl;

    // Release requestBody
    delete static_cast<std::string*>(fetch->userData);
    emscripten_fetch_close(fetch);
  };

  emscripten_fetch_t* fetch
    = emscripten_fetch(&attr, "http://localhost:3000/echo");
  if (!fetch) {
    delete requestBody;
    std::cerr << "Failed to start request" << std::endl;
  }
}

// 4. File upload example
void post_request_upload_file_example(
    const std::string& fileName,
    const std::string& fileContent) {
  const std::string boundary =
      "----EmscriptenBoundary7MA4YWxkTrZu0gW";

  // Manually build the multipart body normally generated by curl -F or FormData
  auto* requestBody = new std::string();

  *requestBody += "--" + boundary + "\r\n";
  *requestBody +=
      "Content-Disposition: form-data; "
      "name=\"uploadFile\"; "
      "filename=\"" + fileName + "\"\r\n";
  *requestBody += "Content-Type: text/plain\r\n";
  *requestBody += "\r\n";
  requestBody->append(fileContent.data(), fileContent.size());
  *requestBody += "\r\n";
  *requestBody += "--" + boundary + "--\r\n";

  emscripten_fetch_attr_t attr;
  emscripten_fetch_attr_init(&attr);

  strcpy(attr.requestMethod, "POST");
  attr.attributes =
      EMSCRIPTEN_FETCH_LOAD_TO_MEMORY |
      EMSCRIPTEN_FETCH_REPLACE;

  const std::string contentType =
      "multipart/form-data; boundary=" + boundary;

  const char* headers[] = {
      "Content-Type", contentType.c_str(),
      nullptr
  };

  attr.requestHeaders = headers;
  attr.requestData = requestBody->data();
  attr.requestDataSize = requestBody->size();
  attr.userData = requestBody;

  attr.onsuccess = [](emscripten_fetch_t* fetch) {
    std::string response(fetch->data, fetch->numBytes);

    std::cout << "Status: " << fetch->status << std::endl;
    std::cout << "Response: " << response << std::endl;

    delete static_cast<std::string*>(fetch->userData);
    emscripten_fetch_close(fetch);
  };

  attr.onerror = [](emscripten_fetch_t* fetch) {
    std::string response =
        fetch->data
            ? std::string(fetch->data, fetch->numBytes)
            : std::string{};

    std::cerr << "Status: " << fetch->status << std::endl;
    std::cerr << "Response: " << response << std::endl;

    delete static_cast<std::string*>(fetch->userData);
    emscripten_fetch_close(fetch);
  };

  emscripten_fetch_t* fetch
    = emscripten_fetch(&attr, "http://localhost:3000/upload");
  if (!fetch) {
    delete requestBody;
    std::cerr << "Failed to start upload" << std::endl;
  }
}

// 5. File download example
// Call the download API using the filename returned by the upload response
void get_request_download_file_example(const std::string& fileName) {
  emscripten_fetch_attr_t attr;
  emscripten_fetch_attr_init(&attr);

  strcpy(attr.requestMethod, "GET");
  attr.attributes =
      EMSCRIPTEN_FETCH_LOAD_TO_MEMORY |
      EMSCRIPTEN_FETCH_REPLACE;

  std::string* fileNamePtr = new std::string(fileName);
  attr.userData = static_cast<void*>(fileNamePtr);

  attr.onsuccess = [](emscripten_fetch_t* fetch) {
    std::string response(fetch->data, fetch->numBytes);

    std::cout << "Status: " << fetch->status << std::endl;
    std::cout << "Response: " << response << std::endl;

    // Save the downloaded file to MEMFS
    std::string* pFileName = static_cast<std::string*>(fetch->userData);
    std::ofstream outFile(*pFileName, std::ios::binary);
    outFile.write(fetch->data, fetch->numBytes);
    outFile.close();

    EM_ASM({
      const fileName = UTF8ToString($0);
      const content = FS.readFile(fileName);
      const blob = new Blob([content], {
        type: 'application/octet-stream'
      });

      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = fileName;
      link.click();
      setTimeout(() => {
        URL.revokeObjectURL(url);
      }, 0);

      // Remove the downloaded file from MEMFS
      FS.unlink(fileName);
    }, (*pFileName).c_str());

    delete pFileName;
    emscripten_fetch_close(fetch);
  };

  attr.onerror = [](emscripten_fetch_t* fetch) {
    std::string response =
        fetch->data
            ? std::string(fetch->data, fetch->numBytes)
            : std::string{};

    std::cerr << "Status: " << fetch->status << std::endl;
    std::cerr << "Response: " << response << std::endl;

    delete static_cast<std::string*>(fetch->userData);
    emscripten_fetch_close(fetch);
  };

  emscripten_fetch_t* fetch =
    emscripten_fetch(&attr, ("http://localhost:3000/download/" + fileName).c_str());
  if (!fetch) {
    delete fileNamePtr;
    std::cerr << "Failed to start download" << std::endl;
  }
}

EMSCRIPTEN_BINDINGS(my_module) {
  emscripten::function("get_request_example", &get_request_example);
  emscripten::function("get_request_with_auth_example", &get_request_with_auth_example);
  emscripten::function("post_request_with_body_example", &post_request_with_body_example);
  emscripten::function("post_request_upload_file_example", &post_request_upload_file_example);
  emscripten::function("get_request_download_file_example", &get_request_download_file_example);
}
